require('frame/util')
require('frame/vec2')
require('frame/vec2_test')
require('frame/class')
require('frame/class_test')
require('frame/zset')
require('frame/zset_test')
require('frame/world')
require('frame/actor')
require('frame/game_thread')
--require('frame/world_test')

require('game/character')
require('game/gun')
require('game/bullet')
require('game/GunBullet')
require('game/player')
require('game/enemy')